[WIP]Edit readme table
Doyaface/chat-space pull request #2
Opened 2019-03-20 12:37 UTC by Doyaface

#WHAT
READMEにデータベース設計を書き加え、また不要な文を削除した
#WHY
データベースのコードを書く際に項目見落としなどの不備を発生させない為

2019-03-20 12:47 UTC, yuki-uchida requested changes

2019-03-20 12:47 UTC, yuki-uchida commented on README.md
> +|group_id|integer|null: false, forex1ign_key: true|
外部キーの場合にはrefference型としましょう

2019-03-20 12:47 UTC, yuki-uchida commented on README.md
> +|message_id|integer|foreign_key: true|
groupテーブルにuser_id、message_idを持つ必要があるか、もう一度考えましょう
多対多の関係ですね

2019-03-21 04:31 UTC, Doyaface commented on README.md
> +|message_id|integer|foreign_key: true|
ご指摘の通り、なんとなくmessege_idを持たせていた為削除いたしました。
user_idはgroupを作る際に必要ではないかと考えて持たしていましたが、再度設計を見直すと不要であると考えましたので削除いたしました

2019-03-21 04:36 UTC, Doyaface commented on README.md
> +|group_id|integer|null: false, forex1ign_key: true|
29,30行目　41,42行目をrefference型としました。
また、６行目にindex 、７行目にuniqueを追加しました。

2019-03-21 04:38 UTC, yuki-uchida requested changes

2019-03-21 04:38 UTC, yuki-uchida commented on README.md
> +|group_name|varchar(255)|null: false|
ここはnameで良いです

2019-03-21 04:38 UTC, yuki-uchida commented on README.md
> +|bodt|text|null: false|
画像だけでも投稿できるようにしましょう

2019-03-21 09:33 UTC, yuki-uchida commented
LGTMです。お疲れ様でした

2019-03-22 09:51 UTC, merged